### ISSUE TITLE
[#15] HomeAPIView UPDATE

### ISSUE THREAD

**Issue by largeredjade** [2024GanzithonPYTHON/6_Ganzi_Backend#31]
homeapiview에 ads들 전부 리턴하면 값이 너무 많아지니까 order_by("?")[:3] 이렇게 하면 랜덤하게 3개씩 리턴되게끔

**Comment by mminjukim** [comment]
+ home api view에 가족 메모 전달 시 가족 멤버들의 프로필 이미지도 리턴돼야 할 것 같슴니다
